### ISSUE TITLE
Error when initializatizing new user

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-ops#20]
```
[I 2020-05-06 11:18:58.297 SingleUserLabApp manager:48] [nb_conda_kernels] enabled, 1 kernels found
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'


Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-labhub", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labhubapp.py", line 42, in main
    return SingleUserLabApp.launch_instance(argv)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser.py", line 558, in initialize
    return super().initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1766, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1380, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 100, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'

```

**Comment by costrouc** [comment]
Similar issue when changing the uid/gid of the user I get the following message

```
'costrouc:x:100000000:20000000:costrouc:/home/costrouc:/bin/false t-potts:x:100000001:20000000:t-potts:/home/t-potts:/bin/false dharhas:x:100000002:20000000:dharhas:/home/dharhas:/bin/false' > /tmp/passwd && echo 'users:x:20000000: admin:x:20000001:' > /tmp/group && ln -sfn /home/shared $HOME/shared]) for Container "notebook" in Pod "jupyter-costrouc_dev(30768244-8f9b-11ea-aedb-42010a80000b)" failed - error: command '/bin/sh -c echo 'costrouc:x:100000000:20000000:costrouc:/home/costrouc:/bin/false t-potts:x:100000001:20000000:t-potts:/home/t-potts:/bin/false dharhas:x:100000002:20000000:dharhas:/home/dharhas:/bin/false' > /tmp/passwd && echo 'users:x:20000000: admin:x:20000001:' > /tmp/group && ln -sfn /home/shared $HOME/shared' exited with 1: ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored. ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored. ln: failed to create symbolic link '//shared': Permission denied , message: "ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.\nERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.\nln: failed to create symbolic link '//shared': Permission denied\n"
```

**Comment by costrouc** [comment]
Errors due to permissions in home directory. Current solution is not robuts to changing a user's uid. But is a good solution and will not affect performance.
