### ISSUE TITLE
Can't spin up large worker on datum qhub

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-ops#41]
Currently can't spin up larger workers on datum qhub. This is the code to attempt to spin up a large worker:

```python
import dask_gateway
from dask.distributed import Client

gateway = dask_gateway.Gateway()
options = gateway.cluster_options()
options.environment = 'aws-datum'
options.profile = 'Large Worker'
cluster = gateway.new_cluster(options)
cluster.scale(10)
```

It results in this error from the logs on the dask gateway pod:

```bash
[E 2020-06-02 13:55:15.971 DaskGateway] Error while starting worker <dask_gateway_server.objects.Worker object at 0x7f3754263d90>
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/app.py", line 1008, in start_worker
        await self._start_worker(cluster, worker)
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/app.py", line 979, in _start_worker
        async for state in cluster.manager.start_worker(worker.name, cluster.state):
      File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/managers/kubernetes.py", line 713, in start_worker
        None, self.kube_client.create_namespaced_pod, self.namespace, pod
      File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6115, in create_namespaced_pod
        (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6206, in create_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
        _request_timeout=_request_timeout)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request
        body=body)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 266, in POST
        body=body)
      File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (422)
    Reason: Unprocessable Entity
    HTTP response headers: HTTPHeaderDict({'Audit-Id': '81d566a1-b58a-45a7-b61e-1a8613ca1f69', 'Content-Type': 'application/json', 'Date': 'Tue, 02 Jun 2020 13:55:15 GMT', 'Content-Length': '493'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"dask-gateway-tylerpotts-worker-b9f654725d75492e8f32246db72f68de\" is invalid: spec.containers[0].volumeMounts[1].name: Not found: \"conda-store\"","reason":"Invalid","details":{"name":"dask-gateway-tylerpotts-worker-b9f654725d75492e8f32246db72f68de","kind":"Pod","causes":[{"reason":"FieldValueNotFound","message":"Not found: \"conda-store\"","field":"spec.containers[0].volumeMounts[1].name"}]},"code":422}
```

**Comment by tylerpotts** [comment]
This is resolved
